language: clojure
script:
  - lein2 test
  - lein2 with-profile +1.3 test
  - lein2 with-profile +1.4 test
  - lein2 with-profile +1.5 test
  - lein2 with-profile +1.6 test
  - lein2 with-profile +1.7 test
jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
  - oraclejdk8
